### ISSUE TITLE
DailyCodingProblem!

### ISSUE THREAD

**Issue by mrpalide** [mehdieidi/MehdiEidi#1]
Hey Mehdi! What's up?

Check here: https://www.dailycodingproblem.com/

If you was interest call me back. I would like to discuss about problems with one or two others. I asked [Mahdi](https://github.com/mahdiZarepoor/AdventOfCodeSolution/issues/1) and [AmirReza](https://github.com/amirkhaki/resume/issues/1) too. ;)

Good luck!

**Comment by mehdieidi** [comment]
Hey Mohammad :D
How are you doing ?

Thanks for sharing the problem with me.
I'll try to work it out. I will let you know if I come up with anything interesting :D

But I may be slow to respond due to damn university assignments :/

Take care!
